{{- define "container-host-profiler" -}}
- name: host-profiler
  image: "{{ include "ddot-ebpf-image" . }}"
  imagePullPolicy: {{ .Values.datadog.hostProfiler.imagePullPolicy | default .Values.agents.image.pullPolicy }}
  {{- if .Values.agents.lifecycle }}
  lifecycle:
{{ toYaml .Values.agents.lifecycle | indent 4 }}
  {{- end }}
  command:
    - "host-profiler"
    - "--core-config={{ template "datadog.confPath" .  }}/datadog.yaml"
{{ include "generate-security-context" (dict "securityContext" .Values.agents.containers.hostProfiler.securityContext "targetSystem" .Values.targetSystem "seccomp" (include "host-profiler-seccomp-profile" .) "kubeversion" .Capabilities.KubeVersion.Version "apparmor" (and .Values.agents.podSecurity.apparmor.enabled .Values.datadog.hostProfiler.apparmor)) | nindent 2 }}
  resources:
{{ toYaml .Values.agents.containers.hostProfiler.resources | indent 4 }}
{{- if or .Values.datadog.envFrom .Values.agents.containers.hostProfiler.envFrom }}
  envFrom:
{{- if .Values.datadog.envFrom }}
{{ .Values.datadog.envFrom | toYaml | indent 4 }}
{{- end }}
{{- if .Values.agents.containers.hostProfiler.envFrom }}
{{ .Values.agents.containers.hostProfiler.envFrom | toYaml | indent 4 }}
{{- end }}
{{- end }}
  env:
    {{- include "containers-common-env" . | nindent 4 }}
    {{- include "containers-cluster-agent-env" . | nindent 4 }}
    - name: DD_AGENT_IPC_PORT
      value: "5009"
    - name: DD_AGENT_IPC_CONFIG_REFRESH_INTERVAL
      value: "60"
    - name: DD_LOG_LEVEL
      value: {{ .Values.agents.containers.hostProfiler.logLevel | default .Values.datadog.logLevel | quote }}
    {{- include "additional-env-entries" .Values.agents.containers.hostProfiler.env | indent 4 }}
    {{- include "additional-env-dict-entries" .Values.agents.containers.hostProfiler.envDict | indent 4 }}
  volumeMounts:
    - name: logdatadog                                                                                                                                                 
      mountPath: {{ template "datadog.logDirectoryPath" . }}                                                                                                           
      readOnly: false                                                                                                                   
    - name: tracingfs
      mountPath: /sys/kernel/tracing
      # cilium/ebpf writes on /sys/kernel/tracing as fallback to old kernel limitations
      # Upstream has (at the time of writing) as minimum kernel version 5.10 which does not have that limitation
      # anymore; readOnly can be enforced.
      # https://github.com/cilium/ebpf/blob/9f87aafaeb37c579ad1e3f5729462d8540200504/link/kprobe.go#L294-L299
      readOnly: true
    - name: config
      mountPath: {{ template "datadog.confPath" . }}
      readOnly: true
    {{- if (not .Values.providers.gke.autopilot) }}
    - name: auth-token
      mountPath: {{ template "datadog.confPath" . }}/auth
      readOnly: true
    {{- end }}
    - name: {{ include "datadog.agentRunVolumeName" . }}
      mountPath: /opt/datadog-agent/run
      readOnly: false
    - name: tmpdir
      mountPath: /tmp
      readOnly: false # Need RW for tmp directory
    {{- include "container-crisocket-volumemounts" . | nindent 4 }}
    {{- include "container-cloudinit-volumemounts" . | nindent 4 }}
    {{- if .Values.datadog.kubelet.hostCAPath }}
{{ include "datadog.kubelet.volumeMount" . | indent 4 }}
    {{- end }}
{{- if .Values.agents.volumeMounts }}
{{ toYaml .Values.agents.volumeMounts | indent 4 }}
{{- end }}
{{- if .Values.agents.containers.hostProfiler.volumeMounts }}
{{ toYaml .Values.agents.containers.hostProfiler.volumeMounts | indent 4 }}
{{- end }}
{{- end -}}
