{{- define "host-profiler-seccomp-init" -}}
{{- $hostProfilerSecurityContext := .Values.agents.containers.hostProfiler.securityContext | default dict -}}
{{- $selinuxOptions := $hostProfilerSecurityContext.seLinuxOptions | default dict -}}
{{- $selinuxType := $selinuxOptions.type | default "spc_t" -}}
{{- $securityContext := mergeOverwrite
      (deepCopy (.Values.agents.containers.initContainers.securityContext | default dict))
      (dict "seLinuxOptions" (dict "type" $selinuxType))
-}}
- name: host-profiler-seccomp-setup
  securityContext:
{{ toYaml $securityContext | indent 4 }}
  image: "{{ include "ddot-ebpf-image" . }}"
  imagePullPolicy: {{ .Values.datadog.hostProfiler.imagePullPolicy | default .Values.agents.image.pullPolicy }}
  {{- $dst := printf "/host%s/%s" .Values.datadog.hostProfiler.seccompRoot (include "host-profiler-seccomp-name" .) }}
  command:
  {{- if .Values.datadog.hostProfiler.loggingSeccomp }}
  - sh
  - -c
  - "if [ -f /etc/dd-host-profiler/logging-seccomp.json ]; then cp /etc/dd-host-profiler/logging-seccomp.json {{ $dst }}; else echo 'WARNING: logging-seccomp.json not found in image, falling back to default seccomp profile'; cp /etc/dd-host-profiler/seccomp.json {{ $dst }}; fi"
  {{- else }}
  - cp
  - /etc/dd-host-profiler/seccomp.json
  - {{ $dst }}
  {{- end }}
  volumeMounts:
  - name: host-profiler-seccomp-root
    mountPath: /host{{ .Values.datadog.hostProfiler.seccompRoot }}
    mountPropagation: {{ .Values.datadog.hostVolumeMountPropagation }}
    readOnly: false # Need RW for seccomp-root
  resources:
{{ toYaml .Values.agents.containers.initContainers.resources | indent 4 }}
{{- end -}}
