{{- $dcaImageTag := .Values.clusterAgent.image.tag | toString }}
{{- if and .Values.datadog.kubeActions.enabled (eq (include "cluster-agent-enabled" .) "true") (or .Values.clusterAgent.image.doNotCheckTag (hasPrefix "latest" $dcaImageTag) (semverCompare ">=7.79.0-0" $dcaImageTag)) }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: {{ template "datadog.fullname" . }}-kubeactions
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - get
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: {{ template "datadog.fullname" . }}-kubeactions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "datadog.fullname" . }}-kubeactions
subjects:
  - kind: ServiceAccount
    name: {{ if .Values.clusterAgent.rbac.create }}{{ template "datadog.fullname" . }}-cluster-agent{{ else }}"{{ .Values.clusterAgent.rbac.serviceAccountName }}"{{ end }}
    namespace: {{ .Release.Namespace }}
{{- end }}
