{{- if or .Values.clusterAgent.createPodDisruptionBudget .Values.clusterAgent.pdb.enable -}}
apiVersion: {{ template "policy.poddisruptionbudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "datadog.fullname" . }}-cluster-agent
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
spec:
  minAvailable: {{ .Values.clusterAgent.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      app: {{ template "datadog.fullname" . }}-cluster-agent
{{- end -}}
