{{- if and .Values.otelAgentGateway.enabled (eq (include "otel-agent-gateway.controllerType" .) "Deployment") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "datadog.fullname" . }}-otel-agent-gateway
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
    app.kubernetes.io/component: otel-agent-gateway
    {{- if .Values.otelAgentGateway.additionalLabels }}
{{ toYaml .Values.otelAgentGateway.additionalLabels | indent 4 }}
    {{- end }}
{{ include "provider-labels" . | indent 4 }}
  {{- if .Values.otelAgentGateway.deploymentAnnotations }}
  annotations: {{ toYaml .Values.otelAgentGateway.deploymentAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.otelAgentGateway.replicas | default 1 }}
  revisionHistoryLimit: {{ .Values.otelAgentGateway.revisionHistoryLimit }}
  strategy:
{{- if .Values.otelAgentGateway.strategy }}
{{ toYaml .Values.otelAgentGateway.strategy | indent 4 }}
{{- else }}
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
{{- end }}
  selector:
    matchLabels:
      app: {{ template "datadog.fullname" . }}-otel-agent-gateway
        {{- if .Values.otelAgentGateway.podLabels }}
{{ toYaml .Values.otelAgentGateway.podLabels | indent 6 }}
        {{- end }}
{{- include "otel-agent-gateway.podTemplate" . }}
{{ end }}
