{{- $cn := printf "%s-root-ca" .Release.Name -}}
{{- $ca := genCA $cn 3650 -}}
apiVersion: v1
kind: Secret
metadata:
  name: datadog-agent-ipc-root-ca-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ipc_ca.crt: {{ $ca.Cert | b64enc | quote }}
  ipc_ca.key: {{ $ca.Key | b64enc | quote }}
