{{- if .Values.installAgents }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datadog-operator.agentInstallFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog-operator.labels" . | indent 4 }}
data:
  agent-config.yaml: |
    apiVersion: datadoghq.com/v2alpha1
    kind: DatadogAgent
    metadata:
      name: datadog-agent
    spec:
      global:
        {{- if or .Values.site (eq (include "is-valid-endpoint-config-data" (list . "dd-site")) "true") }}
        site: {{ default .Values.site (include "get-endpoint-config-data-key" (list . "dd-site")) }}
        {{- end }}
        {{- if or .Values.dd_url (eq (include "is-valid-endpoint-config-data" (list . "dd-url")) "true") }}
        endpoint:
          url: {{ default .Values.dd_url (include "get-endpoint-config-data-key" (list . "dd-url")) }}
        {{- end }}
        credentials:
          apiSecret:
            secretName: __DD_API_SECRET_NAME__
            keyName: api-key
          {{- if eq (include "should-set-dd-app-key" .) "true" }}
          appSecret:
            secretName: __DD_APP_SECRET_NAME__
            keyName: app-key
          {{- end }}
      features:
        liveContainerCollection:
          enabled: true
        liveProcessCollection:
          enabled: true
        logCollection:
          enabled: true
          containerCollectAll: true
        apm:
          enabled: true
        npm:
          enabled: true
{{- end }}
