apiVersion: v2
name: cloudprem
description: Datadog CloudPrem
type: application
version: 0.3.2
# This is the version of the "application". Right now, we follow the image version.
appVersion: v0.1.25
home: https://www.datadoghq.com/
icon: https://static.datadoghq.com/static/images/logos/_datadog_avatar.svg
maintainers:
  - name: Datadog
    email: support@datadoghq.com
