apiVersion: v1
name: datadog-crds
description: Datadog Kubernetes CRDs chart
version: 2.20.0-dev.6
appVersion: "1"
keywords:
- monitoring
- alerting
- metric
home: https://www.datadoghq.com
icon: https://static.datadoghq.com/static/images/logos/_datadog_avatar.svg
sources:
- https://app.datadoghq.com/account/settings#agent/kubernetes
- https://github.com/DataDog/datadog-operator
- https://docs.datadoghq.com/agent/cluster_agent/external_metrics
maintainers:
- name: Datadog
  email: support@datadoghq.com
