name: Test CI Scripts

on:
  push:
    paths:
      - '.github/scripts/**'
  pull_request:
    paths:
      - '.github/scripts/**'

# Permission forced by repo-level setting; only elevate on job-level
permissions:
  contents: read

jobs:
  test-ci-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Run CI script unit tests
        run: make unit-test-ci-scripts
