name: Test CI Scripts

on:
  push:
    paths:
      - '.github/scripts/**'
  pull_request:
    paths:
      - '.github/scripts/**'

# Permission forced by repo-level setting; only elevate on job-level
permissions:
  contents: read

jobs:
  test-ci-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Run CI script unit tests
        run: make unit-test-ci-scripts
